import React, { useState, useEffect } from 'react';
import {
  Container,
  Typography,
  Box,
  Grid,
  Paper,
  Card,
  CardContent,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Button,
  ButtonGroup,
  Menu,
  MenuItem,
  LinearProgress,
  Stack,
  Avatar,
  alpha,
  useTheme,
  useMediaQuery,
  Chip,
  IconButton,
  Tooltip,
  TextField,
  InputAdornment,
} from '@mui/material';
import {
  GetApp,
  People,
  Assignment,
  EmojiEvents,
  ExpandMore,
  Group,
  CheckCircle,
  AccessTime,
  TrendingUp,
  Download,
  PictureAsPdf,
  TableChart,
  Search
} from '@mui/icons-material';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Document, Packer, Paragraph, Table as DocxTable, TableCell as DocxTableCell, TableRow as DocxTableRow, TextRun, WidthType } from 'docx';
import { saveAs } from 'file-saver';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip as ChartTooltip,
  Legend,
  ArcElement,
  PointElement,
  LineElement,
} from 'chart.js';
import { Bar, Pie, Line } from 'react-chartjs-2';
import { toast } from 'react-hot-toast';
import api from '../../utils/axios';
import { useAuth } from '../../context/AuthContext';
import { formatTime } from '../../utils/helpers';

ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  ChartTooltip,
  Legend,
  ArcElement,
  PointElement,
  LineElement
);

const Reports = () => {
  const { user } = useAuth();
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('sm'));
  const [loading, setLoading] = useState(true);
  const [period, setPeriod] = useState('weekly');
  const [stats, setStats] = useState({
    engagement: { activeUsers: 0, totalHours: 0, completionRate: 0 },
    achievements: { totalAwarded: 0, topEarners: [] },
    assignments: { total: 0, submitted: 0, graded: 0 },
  });
  const [students, setStudents] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [anchorEl, setAnchorEl] = useState(null);

  const handleClick = (event) => setAnchorEl(event.currentTarget);
  const handleClose = () => setAnchorEl(null);

  useEffect(() => {
    fetchReportData();
  }, [period]);

  const fetchReportData = async () => {
    try {
      setLoading(true);
      const res = await api.get('/api/reports', { params: { period } });
      setStats(res.data);
      setStudents(res.data.students || res.data.studentProgress || []);
    } catch (err) {
      console.error('Error fetching report data:', err);
    } finally {
      setLoading(false);
    }
  };

  const exportToExcel = () => {
    const ws = XLSX.utils.json_to_sheet([
      { Metric: 'Active Users', Value: stats.engagement.activeUsers },
      { Metric: 'Total Study Hours', Value: formatTime(stats.engagement.totalHours) },
      { Metric: 'Completion Rate', Value: `${stats.engagement.completionRate}%` },
      { Metric: 'Achievements Awarded', Value: stats.achievements.totalAwarded },
    ]);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Summary Report');
    XLSX.writeFile(wb, `Academic_Report_${period}.xlsx`);
    handleClose();
  };

  const exportToPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.text('Academic Performance Report', 14, 22);
    doc.setFontSize(11);
    doc.text(`Period: ${period.toUpperCase()}`, 14, 30);
    doc.text(`Generated by: ${user?.name}`, 14, 38);

    autoTable(doc, {
      startY: 45,
      head: [['Metric', 'Value']],
      body: [
        ['Active Users', stats.engagement.activeUsers],
        ['Total Study Hours', formatTime(stats.engagement.totalHours)],
        ['Completion Rate', `${stats.engagement.completionRate}%`],
        ['Achievements Awarded', stats.achievements.totalAwarded],
      ],
    });

    doc.save(`Academic_Report_${period}.pdf`);
    handleClose();
  };

  const exportStudentReport = (student) => {
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.text('Student Progress Report', 14, 22);
    doc.setFontSize(11);
    doc.text(`Student: ${student.name}`, 14, 30);
    doc.text(`Class: ${student.className || 'Unassigned'}`, 14, 36);
    doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 14, 42);

    autoTable(doc, {
      startY: 50,
      head: [['Metric', 'Value']],
      body: [
        ['Watch Time', `${student.videoMinutes} minutes`],
        ['Quiz Average', `${student.score}%`],
        ['Assignment Completion', `${student.assignmentCompletion}%`],
        ['Overall Performance', `${student.overallPerformance}%`],
      ],
      theme: 'grid',
      headStyles: { fillStyle: theme.palette.primary.main }
    });

    doc.save(`${student.name.replace(/\s+/g, '_')}_Progress_Report.pdf`);
    toast.success('Individual report downloaded');
  };

  const exportWeeklyTrend = () => {
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.text('Weekly Engagement Overview', 14, 22);
    doc.setFontSize(11);
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 30);

    autoTable(doc, {
      startY: 40,
      head: [['Day', 'Active Students']],
      body: stats.weeklyActivity.map(a => [a.day, a.active]),
      theme: 'striped',
      headStyles: { fillStyle: theme.palette.primary.main }
    });

    doc.save(`Weekly_Engagement_Report.pdf`);
    toast.success('Engagement report downloaded');
  };

  if (loading) return <LinearProgress />;

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: '#F8FAFC', py: 4 }}>
      <Container maxWidth="xl">
      <Box sx={{ mb: 4, display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 2 }}>
        <Box>
          <Typography variant="h4" fontWeight="900" sx={{ color: 'primary.main' }}>
            Academic Intelligence
          </Typography>
          <Typography variant="body1" color="textSecondary">
            System-wide performance analytics and reporting.
          </Typography>
        </Box>

        <Stack direction="row" spacing={2}>
          <ButtonGroup variant="outlined" size="small">
            <Button onClick={() => setPeriod('weekly')} variant={period === 'weekly' ? 'contained' : 'outlined'}>Weekly</Button>
            <Button onClick={() => setPeriod('monthly')} variant={period === 'monthly' ? 'contained' : 'outlined'}>Monthly</Button>
            <Button onClick={() => setPeriod('yearly')} variant={period === 'yearly' ? 'contained' : 'outlined'}>Yearly</Button>
          </ButtonGroup>
          
          <Button
            variant="contained"
            startIcon={<GetApp />}
            onClick={handleClick}
            sx={{ bgcolor: 'primary.main', '&:hover': { bgcolor: 'primary.dark' } }}
          >
            Export
          </Button>
          <Menu anchorEl={anchorEl} open={Boolean(anchorEl)} onClose={handleClose}>
            <MenuItem onClick={exportToExcel}>Export to Excel</MenuItem>
            <MenuItem onClick={exportToPDF}>Export to PDF</MenuItem>
          </Menu>
        </Stack>
      </Box>

      <Box sx={{ mb: 4 }}>
        <TextField
          fullWidth
          placeholder="Search by student name or class..."
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          InputProps={{
            startAdornment: (
              <InputAdornment position="start">
                <Search sx={{ color: 'text.secondary' }} />
              </InputAdornment>
            ),
            sx: { borderRadius: 3, bgcolor: 'white', boxShadow: '0 4px 12px rgba(0,0,0,0.03)', border: '1px solid #E2E8F0' }
          }}
        />
      </Box>

      {/* Groups by Class */}
      {Object.entries(
        students
          .filter(s => 
            s.name.toLowerCase().includes(searchTerm.toLowerCase()) || 
            (s.className && s.className.toLowerCase().includes(searchTerm.toLowerCase()))
          )
          .reduce((acc, student) => {
            const className = student.className || 'Unassigned';
            if (!acc[className]) acc[className] = [];
            acc[className].push(student);
            return acc;
          }, {})
      ).map(([className, classStudents]) => (
        <Paper key={className} sx={{ borderRadius: 4, overflow: 'hidden', mb: 4 }}>
          <Box sx={{ p: 3, bgcolor: alpha(theme.palette.primary.main, 0.05), borderBottom: '1px solid #E2E8F0', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <Typography variant="h6" fontWeight="bold" sx={{ color: 'primary.main' }}>{className}</Typography>
            <Chip label={`${classStudents.length} Students`} size="small" variant="filled" sx={{ bgcolor: 'primary.main', color: 'white' }} />
          </Box>
          <TableContainer>
            <Table>
              <TableHead>
                <TableRow sx={{ bgcolor: '#F8FAFC' }}>
                  <TableCell sx={{ fontWeight: 'bold' }}>Student Name</TableCell>
                  <TableCell sx={{ fontWeight: 'bold' }}>Watch Time</TableCell>
                  <TableCell sx={{ fontWeight: 'bold' }}>Class</TableCell>
                  <TableCell sx={{ fontWeight: 'bold' }}>Quiz Avg</TableCell>
                  <TableCell sx={{ fontWeight: 'bold' }}>Assignments</TableCell>
                  <TableCell sx={{ fontWeight: 'bold' }}>Performance</TableCell>
                  <TableCell align="right" sx={{ fontWeight: 'bold' }}>Download Report</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {classStudents.map((student) => (
                  <TableRow key={student.userId} hover>
                    <TableCell>
                      <Stack direction="row" spacing={2} alignItems="center">
                        <Avatar sx={{ width: 32, height: 32, bgcolor: alpha(theme.palette.primary.main, 0.1), color: theme.palette.primary.main, fontSize: '0.8rem', fontWeight: 'bold' }}>
                          {student.name.charAt(0)}
                        </Avatar>
                        <Typography variant="body2" fontWeight="600">{student.name}</Typography>
                      </Stack>
                    </TableCell>
                    <TableCell>
                      <Stack direction="row" spacing={1} alignItems="center">
                        <AccessTime sx={{ fontSize: 16, color: 'text.secondary' }} />
                        <Typography variant="body2">{student.videoMinutes}m</Typography>
                      </Stack>
                    </TableCell>
                    <TableCell>
                      <Chip 
                        label={student.className || 'Unassigned'} 
                        size="small" 
                        variant="outlined"
                        sx={{ fontSize: '0.75rem', fontWeight: 600, color: 'text.secondary' }}
                      />
                    </TableCell>
                    <TableCell>
                      <Box display="flex" alignItems="center" gap={1}>
                        <Typography variant="body2" fontWeight="bold">{student.score}%</Typography>
                        <LinearProgress 
                          variant="determinate" 
                          value={student.score} 
                          sx={{ width: 60, height: 6, borderRadius: 3, bgcolor: alpha('#EAB308', 0.1), '& .MuiLinearProgress-bar': { bgcolor: '#EAB308' } }} 
                        />
                      </Box>
                    </TableCell>
                    <TableCell>
                      <Typography variant="body2">{student.assignmentCompletion}%</Typography>
                    </TableCell>
                    <TableCell>
                      <Box sx={{ width: '100%', display: 'flex', alignItems: 'center', gap: 2 }}>
                        <Box sx={{ flex: 1 }}>
                          <LinearProgress 
                            variant="determinate" 
                            value={student.overallPerformance} 
                            sx={{ 
                              height: 8, 
                              borderRadius: 4,
                              bgcolor: alpha(theme.palette.primary.main, 0.1),
                              '& .MuiLinearProgress-bar': {
                                bgcolor: student.overallPerformance > 80 ? theme.palette.primary.main : student.overallPerformance > 50 ? theme.palette.secondary.main : '#F43F5E'
                              }
                            }} 
                          />
                        </Box>
                        <Typography variant="caption" fontWeight="bold">
                          {student.overallPerformance}%
                        </Typography>
                      </Box>
                    </TableCell>
                    <TableCell align="right">
                      <Tooltip title="Download Report">
                        <IconButton 
                          size="small" 
                          onClick={() => exportStudentReport(student)}
                          sx={{ color: 'primary.main', bgcolor: alpha(theme.palette.primary.main, 0.1), '&:hover': { bgcolor: alpha(theme.palette.primary.main, 0.2) } }}
                        >
                          <Download fontSize="small" />
                        </IconButton>
                      </Tooltip>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
        </Paper>
      ))}

      {/* Weekly Trend - Shown only if there is activity */}
      {stats.weeklyActivity?.length > 0 && (
        <Paper sx={{ p: 4, borderRadius: 4, bgcolor: 'white', boxShadow: '0 4px 20px rgba(0,0,0,0.03)', border: '1px solid #E2E8F0' }}>
          <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
            <Typography variant="h6" fontWeight="bold" sx={{ color: 'primary.main' }}>
              Weekly Engagement Overview
            </Typography>
            <Button 
              size="small" 
              startIcon={<GetApp />} 
              onClick={exportWeeklyTrend}
              sx={{ color: 'primary.main' }}
            >
              Download Data
            </Button>
          </Box>
          <Box sx={{ height: '300px' }}>
            <Line
              data={{
                labels: stats.weeklyActivity.map(a => a.day),
                datasets: [{
                  label: 'Active Students',
                  data: stats.weeklyActivity.map(a => a.active),
                  borderColor: theme.palette.primary.main,
                  backgroundColor: alpha(theme.palette.primary.main, 0.1),
                  fill: true,
                  tension: 0.4,
                  pointRadius: 4,
                  pointBackgroundColor: theme.palette.primary.main,
                  borderWidth: 3
                }]
              }}
              options={{
                maintainAspectRatio: false,
                plugins: { legend: { display: false } },
                scales: {
                  y: { 
                    beginAtZero: true, 
                    ticks: { stepSize: 1 },
                    grid: { color: alpha('#E2E8F0', 0.5) }
                  },
                  x: { grid: { display: false } }
                }
              }}
            />
          </Box>
        </Paper>
      )}

      {students.length === 0 && !loading && (
        <Paper sx={{ p: 8, textAlign: 'center', borderRadius: 4 }}>
          <Typography color="textSecondary">No student performance data available for the selected period.</Typography>
        </Paper>
      )}


      </Container>
    </Box>
  );
};

export default Reports;
